pipeline {

  agent none

  options {
    ansiColor('xterm')
    disableConcurrentBuilds()
    skipDefaultCheckout(true)
    skipStagesAfterUnstable()
  }

  environment {

    CF_API   = 'https://api.cf.eu10-004.hana.ondemand.com'
    CF_ORG   = 'Kuwait Petroleum Italia S.p.A.'
    CF_SPACE = 'FlexibleV1'

    GH_ORGANIZATION = 'KPICorporate'
    REPOSITORY_NAME = 'sap-btp-cicd'
    JENKINS_ENV     = 'PROD'
    
    NEXUS_URL  = 'https://nexus.automation-platform.eu-west-1.aws.q8int.com'
	  NEXUS_REPO = 'sap-btp-raw-dev-hosted'
  }

  stages {

    /* =========================================================
     * CHECKOUT
     * ========================================================= */
    stage('Checkout') {

      agent {
        kubernetes(k8sAgent(
          cloud: 'kubernetes',
          podTemplate: 'gh',
          serviceAccount: 'jenkins'
        ))
      }

      steps {

        container('gh') {

          script {

            def repoUrl =
              "git@github.com:${env.GH_ORGANIZATION}/${env.REPOSITORY_NAME}.git"

            def dkName = (
              "AUT-PLAT-${env.JENKINS_ENV}-DK-${env.REPOSITORY_NAME}"
            ).toUpperCase()

            cloneWithDK(
              [
                repo_url: repoUrl,
                dk       : dkName,
                branch   : 'main'
              ]
            ) {

              dir("${env.REPOSITORY_NAME}") {

                sh '''
                  echo "Repository checked out"
                  git status
                '''
              }
            }

            stash(
              name: 'source',
              includes: '**',
              useDefaultExcludes: false
            )
          }
        }
      }
    }

    stage('Bootstrap Tag (one-shot)') {

      agent {
        kubernetes(k8sAgent(
          cloud: 'kubernetes',
          podTemplate: 'sap-btp',
          serviceAccount: 'jenkins'
        ))
      }

      environment {
        TAG_PREFIX = 'cap' // ui5 | workflow | cap
        INITIAL_VERSION = '2.0.0'
      }

      steps {

        container('sap-btp') {

          unstash 'source'

          withAwsSecret([
            secret_id: "SM-AUT-PLAT-PROD-SAP-BTP-GH-TOKEN".toUpperCase(),
            type: "keyvalue"
          ]) {

            script {

              def githubToken = env.token

              dir("${env.REPOSITORY_NAME}") {

                sh """
                  set -e

                  git remote set-url origin \
                    https://x-access-token:${githubToken}@github.com/${GH_ORGANIZATION}/${REPOSITORY_NAME}.git

                  git fetch --tags --force

                  TAG="${TAG_PREFIX}-v${INITIAL_VERSION}"

                  echo "Checking bootstrap tag: \$TAG"

                  if git tag | grep -q "^\${TAG_PREFIX}-v"; then
                    echo "Tags already exist → skip bootstrap"
                  else
                    echo "Creating bootstrap tag \$TAG"
                    git tag "\$TAG"
                    git push origin "\$TAG"
                  fi
                """
              }
            }
          }
        }
      }
    }

    /* =========================================================
     * SEMANTIC RELEASE
     * ========================================================= */
    stage('Semantic Release') {

      agent {
        kubernetes(k8sAgent(
          cloud: 'kubernetes',
          podTemplate: 'sap-btp',
          serviceAccount: 'jenkins'
        ))
      }

      steps {

        container('sap-btp') {

          unstash 'source'

          withAwsSecret([
            secret_id: "SM-AUT-PLAT-PROD-SAP-BTP-GH-TOKEN".toUpperCase(),
            type: "keyvalue"
          ]) {

            script {

              def githubToken = env.token

              dir("${env.REPOSITORY_NAME}") {

                sh '''
                  node -v
                  npm -v
                '''

                sh """
                  git remote set-url origin \
                    https://x-access-token:${githubToken}@github.com/${GH_ORGANIZATION}/${REPOSITORY_NAME}.git
                """

                withEnv([
                  "GITHUB_TOKEN=${githubToken}",
                  "GH_TOKEN=${githubToken}",
                  "GIT_BRANCH=main",
                  "BRANCH_NAME=main",
                  "CI=true",
                  "NO_COLOR=1",
                  "FORCE_COLOR=0"
                ]) {

                  sh '''
					          set -e

					          echo "Installing semantic-release"

					          npm install --no-save \
					            semantic-release \
					            @semantic-release/commit-analyzer \
					            @semantic-release/release-notes-generator \
					            @semantic-release/git

					          echo "Running semantic-release dry-run"

					          npx semantic-release \
                      --branches main \
                      --tag-format 'cap-v${version}' \
                      --no-ci \
                      --plugins \
                        @semantic-release/commit-analyzer \
                        @semantic-release/release-notes-generator \
                        @semantic-release/git \
                      > semantic.log 2>&1 || true

                    cat semantic.log

                    if grep -q "no new version is released" semantic.log; then
                      echo "NO_RELEASE=true" > version.env
                      echo "VERSION=" >> version.env
                      echo "No new release"
                    else
                      VERSION=$(grep 'next release version is' semantic.log | grep -Eo '[0-9]+[.][0-9]+[.][0-9]+')

                      if [ -z "$VERSION" ]; then
                        echo "ERROR: Unable to detect version"
                        exit 1
                      fi

                      echo "VERSION=$VERSION" > version.env
                      echo "NO_RELEASE=false" >> version.env
                      echo "Next version: $VERSION"
                    fi
				          '''
                }
              }
            }
          }

          stash(
            name: 'version',
            includes: "${env.REPOSITORY_NAME}/version.env"
          )
        }
      }
    }

    stage('Load Version') {

      agent any

      steps {

        unstash 'version'

        script {
          def props = readProperties file: "${env.REPOSITORY_NAME}/version.env"

          env.NO_RELEASE = props.NO_RELEASE
          env.VERSION    = props.VERSION

          echo "Loaded VERSION = ${env.VERSION}"
          echo "Loaded NO_RELEASE = ${env.NO_RELEASE}"
        }
      }
    }

    stage('Release Gate') {

      agent any

      steps {
        unstash 'version'

        script {
          def props = readProperties file: "${env.REPOSITORY_NAME}/version.env"
          env.NO_RELEASE = props.NO_RELEASE
          env.VERSION    = props.VERSION

          echo "Loaded VERSION = ${env.VERSION}"
          echo "Loaded NO_RELEASE = ${env.NO_RELEASE}"

          if (env.NO_RELEASE == "true") {
            echo "No release detected → stopping pipeline"
            
            currentBuild.result = 'UNSTABLE'
            return
          } else {
            echo "Release detected → continuing pipeline"
          }
        }
      }
    }

    /* =========================================================
     * INSTALL
     * ========================================================= */
    stage('Install Dependencies') {

      agent {
        kubernetes(k8sAgent(
          cloud: 'kubernetes',
          podTemplate: 'sap-btp',
          serviceAccount: 'jenkins'
        ))
      }

      steps {

        container('sap-btp') {

          unstash 'source'

          dir("${env.REPOSITORY_NAME}/cap") {

            sh '''
              set -e

              echo "Root install"
              npm install --legacy-peer-deps

              echo "App install"
              [ -f app/package.json ] && (cd app && npm install) || true

              echo "Srv install"
              [ -f srv/package.json ] && (cd srv && npm install) || true

              echo "DB install"
              [ -f db/package.json ] && (cd db && npm install) || true

              echo "Dedupe"
              npm dedupe || true
            '''
          }

          stash(
            name: 'installed-source',
            includes: '**',
            useDefaultExcludes: false
          )
        }
      }
    }

    /* =========================================================
     * UPDATE VERSION
     * ========================================================= */
    stage('Update Version Files') {

      when {
        expression { env.NO_RELEASE != "true" }
      }

      agent {
        kubernetes(k8sAgent(
          cloud: 'kubernetes',
          podTemplate: 'sap-btp',
          serviceAccount: 'jenkins'
        ))
      }

      steps {

        container('sap-btp') {

          unstash 'installed-source'

          dir("${env.REPOSITORY_NAME}") {

            sh '''
              set -e

              echo "Updating version to $VERSION"

              MTA_FILE="cap/mta.yaml"

              # =========================
              # Aggiorna mta.yaml
              # =========================
              if grep -q "^version:" "$MTA_FILE"; then
                sed -i "s/^version:.*/version: $VERSION/" "$MTA_FILE"
              else
                echo "version: $VERSION" >> "$MTA_FILE"
              fi

              echo "Updated $MTA_FILE"
              cat "$MTA_FILE"

              # =========================
              # Aggiorna package.json e package-lock.json
              # =========================
              cd cap

              npm version "$VERSION" --no-git-tag-version

              echo "===== package.json ====="
              cat package.json

              echo "===== package-lock.json ====="
              cat package-lock.json
            '''
          }

          stash(
            name: 'updated-source',
            includes: '**',
            useDefaultExcludes: false
          )
        }
      }
    }

    /* =========================================================
     * CLEAN
     * ========================================================= */
    stage('Clean Workspace') {

      agent {
        kubernetes(k8sAgent(
          cloud: 'kubernetes',
          podTemplate: 'sap-btp',
          serviceAccount: 'jenkins'
        ))
      }

      steps {

        container('sap-btp') {

          unstash 'updated-source'

          dir("${env.REPOSITORY_NAME}/cap") {

            sh '''
              set -e

              rm -rf gen
              rm -rf mta_archives
              rm -rf node_modules
              rm -rf kupit-flexiblewf-cap-* || true
            '''
          }

          stash(
            name: 'clean-source',
            includes: '**',
            useDefaultExcludes: false
          )
        }
      }
    }

    /* =========================================================
     * BUILD MTA
     * ========================================================= */
    stage('Build MTA') {

      agent {
        kubernetes(k8sAgent(
          cloud: 'kubernetes',
          podTemplate: 'sap-btp',
          serviceAccount: 'jenkins'
        ))
      }

      steps {

        container('sap-btp') {

          unstash 'clean-source'

          dir("${env.REPOSITORY_NAME}/cap") {

            sh '''
              set -e

              node -v
              npm -v
              cds --version
              mbt --version

              rm -rf gen mta_archives

              echo "Building CAP project"

              npx cds build

              echo "Installing production deps"

              cd gen/srv
              npm install --omit=dev

              cd ../../

              echo "Building MTAR"

              mbt build -p cf -t mta_archives

              echo "Generated MTAR"

              ls -lah mta_archives
            '''
          }

          stash(
            name: 'mtar',
            includes: "${env.REPOSITORY_NAME}/cap/mta_archives/*.mtar",
            useDefaultExcludes: false
          )
        }
      }
    }

    /* =========================================================
	 * PUBLISH MTAR TO NEXUS
     * ========================================================= */
	stage('Publish MTAR to Nexus') {

		agent {
			kubernetes(k8sAgent(
			cloud: 'kubernetes',
			podTemplate: 'sap-btp',
			serviceAccount: 'jenkins'
			))
		}

		steps {

			container('sap-btp') {

			unstash 'mtar'
			unstash 'version'
			
			withAwsSecret([
			  secret_id: "SM-AUT-PLAT-PROD-NEXUS-SAP-BTP-CREDENTIALS".toUpperCase(),
			  type: "keyvalue"
			]) {
			
			  script {
				
				def nexusToken = env.token

        withEnv([
						"NEXUS_TOKEN_B64=${nexusToken}"
					]) {

				dir("${env.REPOSITORY_NAME}/cap") {

					sh '''
						set -e					

					  VERSION=$(grep '^VERSION=' ../version.env | cut -d '=' -f2)

					  MTAR_FILE=$(ls mta_archives/*.mtar | head -n 1)

					  MTAR_NAME=$(basename "$MTAR_FILE")

					  echo "================================================="
					  echo "Upload MTAR to Nexus"
					  echo "================================================="

					  echo "Artifact: $MTAR_NAME"
					  echo "Version : $VERSION"

					  HTTP_CODE=$(curl \
					  --insecure \
					  -H "Authorization: Basic ${NEXUS_TOKEN_B64}" \
					  -H "Content-Type: application/octet-stream" \
					  --upload-file "$MTAR_FILE" \
					  -w "%{http_code}" \
					  -o /dev/null \
					  "${NEXUS_URL}/repository/${NEXUS_REPO}/${VERSION}/${MTAR_NAME}")

				    echo "HTTP CODE: $HTTP_CODE"

				    if [ "$HTTP_CODE" != "201" ]; then
					    echo "ERROR: Upload failed"
					    exit 1
				    fi

				    echo "Upload completed successfully"
			    '''
        }  
      }  
	  }
	 }
  }
 }
}

    /* =========================================================
     * DEPLOY
     * ========================================================= */
    stage('Deploy') {

      agent {
        kubernetes(k8sAgent(
          cloud: 'kubernetes',
          podTemplate: 'sap-btp',
          serviceAccount: 'jenkins'
        ))
      }

      steps {

        container('sap-btp') {

          unstash 'updated-source'
          unstash 'mtar'

          withAwsSecret([
            secret_id: "SM-AUT-PLAT-PROD-SAP-BTP-DEPLOY-CREDENTIALS".toUpperCase(),
            type: "keyvalue"
          ]) {
            
            script {

              def btpUser = env.username
              def btpPassword = env.password

              withEnv([
                "CF_USER=${btpUser}",
                "CF_PASSWORD=${btpPassword}"
              ]) {

            dir("${env.REPOSITORY_NAME}/cap") {

              sh '''
                set -e

                cf version

                cf install-plugin -f multiapps || true

                MTAR=$(ls mta_archives/*.mtar | head -n 1)

                cf login \
                  -a "$CF_API" \
                  -u "$CF_USER" \
                  -p "$CF_PASSWORD" \
                  -o "$CF_ORG" \
                  -s "$CF_SPACE"

                cf deploy "$MTAR" -f
              '''
            }
          }
        }
      }
    }
   }
 }

     /* =========================================================
     * COMMIT & TAG
     * ========================================================= */
    stage('Commit & Tag') {

      agent {
        kubernetes(k8sAgent(
          cloud: 'kubernetes',
          podTemplate: 'gh',
          serviceAccount: 'jenkins'
        ))
      }

      steps {

        container('gh') {

          unstash 'updated-source'
          unstash 'version'

          withAwsSecret([
            secret_id: "SM-AUT-PLAT-PROD-SAP-BTP-GH-TOKEN".toUpperCase(),
            type: "keyvalue"
          ]) {

            script {

              def githubToken = env.token
              withEnv(["GITHUB_TOKEN=${githubToken}"]) {

              sh '''
      set -e

    NO_RELEASE=$(grep 'NO_RELEASE=' ${WORKSPACE}/${REPOSITORY_NAME}/version.env | cut -d '=' -f2)

    if [ "$NO_RELEASE" = "true" ]; then
      echo "Skipping commit & tag"
      exit 0
    fi

    VERSION=$(grep 'VERSION=' ${WORKSPACE}/${REPOSITORY_NAME}/version.env | cut -d '=' -f2)

    if [ -z "$VERSION" ]; then
      echo "ERROR: VERSION is empty"
      exit 1
    fi

    echo "Using VERSION: $VERSION"

    TARGET_REPO="sap-btp-wflibero2-cap-cicd"
    TARGET_DIR="/tmp/$TARGET_REPO"

    echo "Target dir: \$TARGET_DIR"

    git config --global user.email "ci@jenkins"
    git config --global user.name "Jenkins CI"

    echo "Cloning repo..."

    rm -rf "$TARGET_DIR"

    git clone https://x-access-token:$GITHUB_TOKEN@github.com/KPICorporate/$TARGET_REPO.git "\$TARGET_DIR"

    if [ ! -d "\$TARGET_DIR/.git" ]; then
      echo "ERROR: clone failed"
      exit 1
    fi
    cd "$TARGET_DIR"
    
    echo "Copy files"

    cp -f ${WORKSPACE}/${REPOSITORY_NAME}/cap/mta.yaml mta.yaml
    cp -f ${WORKSPACE}/${REPOSITORY_NAME}/cap/package.json package.json
    cp -f ${WORKSPACE}/${REPOSITORY_NAME}/cap/package-lock.json package-lock.json

    git add mta.yaml package.json package-lock.json

    if git diff --cached --quiet; then
      echo "No changes to commit"
    else
      git commit -m "chore(release): $VERSION [skip ci]"
      git push origin main
    fi

    git tag -f "v$VERSION"
    
    git push origin main
    git push origin "v$VERSION" --force
  '''
            }
          }
        }
      }
    }
  }
 }
}
 